### PR TITLE
.NET 9 locking

### PR DESCRIPTION
**Pull request by MarkCiliaVincenti**

### CODE REVIEW

**Comment by electricessence** [comment]
Ah!  I thought I fixed this.  Will correct soon.

**Comment by electricessence** [comment]
Wait.  I'm confused.  What's wrong with the implementation as-is?
Why would I introduce another dependency?

**Comment by MarkCiliaVincenti** [comment]
It's a source generator and won't add a transitive dependency.

**Comment by electricessence** [comment]
Ok, but how will it make anything better than how it is?

**Comment by MarkCiliaVincenti** [comment]
It will allow you to use the full feature set of System.Threading.Lock rather than be limited to just the lock keyword. For more information please take a look at https://github.com/MarkCiliaVincenti/Backport.System.Threading.Lock?tab=readme-ov-file#why-not-keep-it-simple

**Comment by electricessence** [comment]
Ok.  Thanks for the intro.  But I see no reason or benefit to introduce this here.
Curious why you thought it would be an improvement for this repo.

**Pull request closed without merging**
